<?php

/**
 * @file
 * Webform Auto Address component.
 */

/**
 * Implements hook_webform_component_info().
 */
function sp_webformautoaddress_webform_component_info() {
  $components = array();

  $components['sp_address_auto'] = array(
    'label' => t('Automcomplete address (SP)'),
    'description' => t('Address is autocompleted through the API of Procurios, using postal code and house number.'),
    'features' => array(
      'analysis' => FALSE,
      'csv' => TRUE,
      'email' => TRUE,
      'email_address' => FALSE,
      'email_name' => FALSE,
      'required' => TRUE,
      'conditional' => TRUE,
      'title_display' => TRUE,
      'title_inline' => TRUE,
      'private' => FALSE,
      'group' => FALSE,
      'spam_analysis' => FALSE,
      'attachment' => FALSE,
    ),
  );

  return $components;
}

/**
 * Implements _webform_defaults_component().
 */
function _webform_defaults_sp_address_auto() {
  return array(
    'name' => '',
    'form_key' => NULL,
    'required' => FALSE,
    'pid' => 0,
    'weight' => 0,
    'extra' => array(
      'key' => '',
      'secret' => '',
      'placeholders' => FALSE,
      'private' => FALSE,
    ),
  );
}

/**
 * Implements _webform_edit_component().
 */
function _webform_edit_sp_address_auto($component) {
  $form = array();

  $form['extra']['placeholders'] = array(
    '#type' => 'checkbox',
    '#title' => t('Placeholders'),
    '#description' => t('Use a placeholder instead of the label. The placeholder will be shown in the field until the user starts entering a value.'),
    '#default_value' => $component['extra']['placeholders'],
  );

  return $form;
}

/**
 * Implements _webform_render_component().
 */
function _webform_render_sp_address_auto($component, $value = NULL, $filter = TRUE) {
  // Wrap the form in a container, in order to correctly apply the weight.
  $elements = array(
    '#type' => 'container',
    '#attached' => array(
      'css' => array(
        drupal_get_path('module', 'sp_webformautoaddress') . '/css/sp_webformautoaddress.css',
      ),
      'js' => array(
        drupal_get_path('module', 'sp_webformautoaddress') . '/js/sp_webformautoaddress.js',
      ),
    ),
    '#weight' => $component['weight'],
    '#theme_wrappers' => array('webform_element'),
    '#webform_component' => $component,
  );

  $elements['postal_code'] = array(
    '#type' => 'textfield',
    '#title' => 'Postcode',
    '#title_display' => $component['extra']['title_display'] ? $component['extra']['title_display'] : 'before',
    '#default_value' => isset($value['postal_code']) ? $value['postal_code'] : '',
    '#required' => $component['required'],
    '#attributes' => array('autcomplete' => 'on'),
    '#size' => 12,
    '#theme_wrappers' => array('webform_element'),
    '#webform_component' => array('type' => $component['type'] . '_postal_code') + $component,
  );

  $elements['house_number'] = array(
    '#type' => 'textfield',
    '#title' => 'Huisnummer',
    '#title_display' => $component['extra']['title_display'] ? $component['extra']['title_display'] : 'before',
    '#default_value' => isset($value['house_number']) ? $value['house_number'] : '',
    '#required' => $component['required'],
    '#attributes' => array(),
    '#size' => 12,
    '#theme_wrappers' => array('webform_element'),
    '#webform_component' => array('type' => $component['type'] . '_house_number') + $component,
  );

  $elements['street_name'] = array(
    '#type' => 'textfield',
    '#title' => 'Straat',
    '#title_display' => $component['extra']['title_display'] ? $component['extra']['title_display'] : 'before',
    '#default_value' => isset($value['street_name']) ? $value['street_name'] : '',
    '#required' => $component['required'],
    '#attributes' => array(),
    '#theme_wrappers' => array('webform_element'),
    '#webform_component' => array('type' => $component['type'] . '_street_name') + $component,
  );

  $elements['city'] = array(
    '#type' => 'textfield',
    '#title' => 'Plaats',
    '#title_display' => $component['extra']['title_display'] ? $component['extra']['title_display'] : 'before',
    '#default_value' => isset($value['city']) ? $value['city'] : '',
    '#required' => $component['required'],
    '#attributes' => array(),
    '#theme_wrappers' => array('webform_element'),
    '#webform_component' => array('type' => $component['type'] . '_city') + $component,
  );

  // Check whether the key and secret are set.
  $elements['postal_code']['#ajax'] = array(
    'callback' => 'sp_webformautoaddress_ajax_callback',
  );
  $elements['house_number']['#ajax'] = array(
    'callback' => 'sp_webformautoaddress_ajax_callback',
  );
  $elements['street_name']['#attributes'] = array(
    'class' => array(drupal_html_class('ajax-callback-street-name--' . $component['form_key'])),
  );
  $elements['city']['#attributes'] = array(
    'class' => array(drupal_html_class('ajax-callback-city--' . $component['form_key'])),
  );

  // Set the label as a place holder.
  if ($component['extra']['placeholders']) {
    $elements['postal_code']['#title_display'] = 'invisible';
    $elements['postal_code']['#attributes']['placeholder'] = 'Postcode';

    $elements['house_number']['#title_display'] = 'invisible';
    $elements['house_number']['#attributes']['placeholder'] = 'Huisnummer';

    $elements['street_name']['#title_display'] = 'invisible';
    $elements['street_name']['#attributes']['placeholder'] = 'Straat';

    $elements['city']['#title_display'] = 'invisible';
    $elements['city']['#attributes']['placeholder'] = 'Plaats';
  }

  return $elements;
}

/**
 * Retrieve street name and city belonging to postal code and house number.
 *
 * Callback for _webform_render_address_auto().
 *
 * NB: Normally, this function should be kept as simple as possible (i.e., just
 *     return the portion of the form that should be adjusted). However, since
 *     Webform doesn't provide the $form_state in a simple manner and we only
 *     provide additional functionallity to help the visitor, we allow us to do
 *     a little bit more in this function.. (otherwise we have to use the
 *     hook_form_alter() function to add AJAX components).
 */
function sp_webformautoaddress_ajax_callback($form, $form_state) {
  // Get the key used for this Webform component.
  $form_key = $form_state['triggering_element']['#webform_component']['form_key'];

  // Get the provided postal code and house number.
  $values = $form_state['values'];
  foreach ($form_state['triggering_element']['#parents'] as $parent) {
    $values = $values[$parent];

    if ($parent == $form_key) {
      break;
    }
  }
  $postal_code = $values['postal_code'];
  $house_number = $values['house_number'];

  // Perform the lookup.
  if (!empty($postal_code) && !empty($house_number)) {
    $data = sp_webformautoaddress_pcapi_lookup($postal_code, $house_number);

    // React on the provided information.
    if (!empty($data)) {

      $commands = array();
      $arguments = array(
        'formKey' => drupal_clean_css_identifier($form_key), // we are selecting by the css class in the ajax call
        'street' => filter_xss($data['street']),
        'city' => filter_xss($data['municipality']),
      );
      $arguments = drupal_json_encode($arguments);
      $commands[] = ajax_command_invoke(NULL, 'SPwebformAutoAddressInject', array($arguments));

      return array(
        '#type' => 'ajax',
        '#commands' => $commands,
      );
    }
  }
}

/**
 * Retrieve street name and city belonging to postal code and house number.
 *
 * This function makes a call to the Procurios API to get the street name and
 * city that is associated with the postal code and house number.
 *
 * @param string $postal_code
 *   The postal code of the address.
 * @param string $house_number
 *   The house number of the address.
 *
 * @return string[]
 *   The name of the street can be found at the index 'street' and the name of
 *   the name of the city at the index 'city' in the array.
 */
function sp_webformautoaddress_pcapi_lookup($postal_code, $house_number) {
  // First, parse the postal code and house number (which should split the
  // addition).
  $postal_code = sp_webformautoaddress_parse_postal_code($postal_code);
  list($house_number, $house_number_addition) = sp_webformautoaddress_parse_house_number($house_number);

  // Both the postal code and the house number should have a value.
  if (empty($postal_code) || empty($house_number)) {
    return array();
  }

  // We prevent making unnecessary lookups by caching results,
  // also wrong lookups!
  $cache_key = 'sp_webformautoaddress:' . $postal_code . ':' . $house_number . ':' . $house_number_addition;

  // Use the local memory as the first level cache.
  $data = &drupal_static(__FUNCTION__);
  if (!isset($data)) {
    // When not stored in local memory, check the cache stored in the database.
    if ($cache = cache_get($cache_key)) {
      $data = $cache->data;
    }
    else {
      $data = procapi_postcode_address_lookup($postal_code, $house_number, $house_number_addition);

      // Store the result in the cache of the database.
      //
      // NB: if the lookup didn't responded in a correct result, we still store
      // a 'mark' in the database. In this way also invalid lookups will be
      // served from cache the next time.
      cache_set($cache_key, $data, 'cache', time() + 900);
    }
  }

  return $data;
}

/**
 * Parse a postal code to be used in the request to Procurios API.
 *
 * @param string $postal_code
 *   The postal code that should be normalized.
 *
 * @return string
 *   The normalized postal code.
 */
function sp_webformautoaddress_parse_postal_code($postal_code) {
  // First, remove any whitespaces.
  $postal_code = str_replace(' ', '', trim($postal_code));

  // If the postal code is in the form of 1234AB, than return the trimmed
  // version.
  if ((boolean) preg_match('~^\d{4}[[:alpha:]]{2}$~', $postal_code)) {
    return $postal_code;
  }

  return '';
}

/**
 * Parse the house number by separating the number from the additional value.
 *
 * @param string $house_number_full
 *   The house number of the address (including an possible addition).
 *
 * @return string[]
 *   Normalized version of the house number, where the first index of the array
 *   contains the number and the second value is the addition.
 */
function sp_webformautoaddress_parse_house_number($house_number_full) {
  // Remove white spaces before and after the provided house number (including
  // addition).
  $house_number_full = trim($house_number_full);

  $house_number = '';
  $house_number_addition = '';
  if (preg_match('~^(?P<house_number>\d+)[^[:alnum:]]*(?P<addition>[[:alnum:]]*)$~', $house_number_full, $match)) {
    $house_number = $match['house_number'];
    $house_number_addition = !empty($match['addition']) ? $match['addition'] : '';
  }

  return array($house_number, $house_number_addition);
}

/**
 * Implements _webform_display_component().
 */
function _webform_display_sp_address_auto($component, $value, $format = 'html') {
  return array(
    '#title' => $component['name'],
    '#weight' => $component['weight'],
    '#theme' => 'webform_display_address_auto',
    '#theme_wrappers' => $format == 'html' ? array('webform_element') : array('webform_element_text'),
    '#post_render' => array('webform_element_wrapper'),
    '#component' => $component,
    '#format' => $format,
    '#value' => isset($value) ? sp_webformautoaddress_display_format($value) : '',
  );
}

/**
 * Implements _webform_theme_component().
 */
function _webform_theme_sp_address_auto() {
  return array(
    'webform_display_address_auto' => array(
      'render element' => 'element',
    ),
  );
}

/**
 * Returns HTML for displaying the address.
 *
 * @param array $variables
 *   An associative array containing:
 *   - element: An associative array containing the properties of the element.
 *     Properties used: #format, #value.
 *
 * @see theme_webform_element
 *
 * @ingroup themeable
 */
function theme_webform_display_sp_address_auto(array $variables) {
  $element = $variables['element'];
  $value = $element['#format'] == 'html' ? check_plain($element['#value']) : $element['#value'];

  return $value !== '' ? $value : ' ';
}

/**
 * Implements _webform_table_component().
 */
function _webform_table_sp_address_auto($component, $value) {
  return check_plain($value['street_name'] . ' ' . $value['house_number']) . '<br />' .
         check_plain($value['postal_code'] . ' ' . $value['city']);
}

/**
 * Implements _webform_csv_headers_component().
 */
function _webform_csv_headers_sp_address_auto($component, $export_options) {
  $header = array();
  $header[0] = array('');
  $header[1] = array($component['name']);
  $header[2] = array();

  $header[2][] = 'Straat';
  $header[2][] = 'Huisnummer';
  $header[2][] = 'Postcode';
  $header[2][] = 'Plaats';

  return $header;
}

/**
 * Implements _webform_csv_data_component().
 */
function _webform_csv_data_sp_address_auto($component, $export_options, $value) {
  $return = array();

  $return[] = $value['street_name'];
  $return[] = $value['house_number'];
  $return[] = $value['postal_code'];
  $return[] = $value['city'];

  return $return;
}

/**
 * Format the address in a textual representation.
 *
 * @param string[] $value
 *   An associative array containing the address information (i.e., street name,
 *   house number, postal code and the city).
 *
 * @return string
 *   A formatted string representing the address.
 */
function sp_webformautoaddress_display_format(array $value) {
  return $value['street_name'] . ' ' . $value['house_number'] . ', ' . $value['postal_code'] . ' ' . $value['city'];
}
